### ISSUE TITLE
Why not replacing bash.ico?

### ISSUE THREAD

**Issue by ilpianista** [alwsl/alwsl#25]
Why do you need to use `archlinux.ico` instead of replacing the existing `bash.ico`?

The thing is other programs, [such as ConEmu](https://github.com/Maximus5/ConEmu/blob/bfb64138f556722bccec88b0ed3e18833d4a55aa/src/ConEmu/OptionsFast.cpp#L2073), uses that as icon for bash.

**Comment by turbo** [comment]
Didn't think about that. That's changing in .6, I've assigned it to the project tracker.

Off topic:

About ConEmu: My experience with ConEmu + the WSL "bash.exe" wrapper was awful so far. It constantly misplaces the cursor and occasionally it doesn't even register arrow keys (for navigating through the history). The bash.exe actually has a routine (use IDA to look for it), that checks if it's hosted by another console. If it is, it spits out a few null-bytes and terminates. MS actually confirmed that in the BoW tracker. Dunno if that causes these glitches in ConEmu, but they have to do some work anyway. I've since switched to using the standard command prompt and tmux, or, on machines where I have Xming installed, terminator.

**Comment by ilpianista** [comment]
Thank you!

I was also using cmd + tmux, but switched to "have everything in one place". However I can confirm your feedbacks about ConEnu :-(

**Comment by turbo** [comment]
Done in private dev branch.

**Comment by Antioch18** [comment]
This wasn't working in the fresh install I just tried. After install I was still seeing the Ubuntu icon.
